run_name: debug_simple_conditional_flow

data_set:
  name: dummy_datasets

preprocessing: []

training:
    comet_project_name: debug_simple_conditional_flow

    splitting_config:
      train_fraction: 0.7
      test_fraction: 0.15

    dataloader_config:
      batch_size: 256
      shuffle: true

    optimizer_config:
      name: adam
      lr: 0.0005
    
    model_config:
      name: conditional_tree_flow
      num_blocks: 24
      mask_fraction: 0.5

    trainer_config:
      max_epochs: 100
