run_name: yule_10_simple_weight_sharing_tuned

# data_set:
#   name: dummy_datasets

# preprocessing: []

data_set:
  name: tree_datasets
  directory: data/mcmc_runs
  glob: "yule-10_*.trees"
  max_files: 100

preprocessing:
  - name: add_taxa_names
  - name: add_clade_information
  - name: remove_tree

training:
    mlflow_experiment_name: yule_10_simple_weight_sharing_tuned

    splitting_config:
      train_fraction: 0.7
      test_fraction: 0.15

    dataloader_config:
      batch_size: 64
      shuffle: true

    optimizer_config:
      name: adamw
      lr: 0.001
      weight_decay: 0.05
    
    model_config:
      name: weight_sharing_tree_flow
      num_blocks: 9
      mask_fraction: 0.2

    trainer_config:
      max_epochs: 20
