run_name: yule_10_simple

# data_set:
#   name: dummy_datasets

# preprocessing: []

data_set:
  name: tree_datasets
  directory: data/mcmc_runs
  glob: "yule-10*.trees"
  max_files: 100

preprocessing:
  - name: add_taxa_names
  - name: add_clade_information
  - name: remove_tree

training:
    splitting_config:
      train_fraction: 0.7
      test_fraction: 0.15

    dataloader_config:
      batch_size: 64
      shuffle: true

    optimizer_config:
      name: adam
      lr: 0.005
      weight_decay: 0.0001
    
    model_config:
      name: conditional_tree_flow
      num_blocks: 8
      mask_fraction: 0.5
      context_embedding_dim: 8

    trainer_config:
      max_epochs: 20
