run_name: debug

data_set:
  name: tree_datasets
  directory: data/mcmc_runs
  glob: "yule-10_5.trees"
  max_files: 100

preprocessing:
  - name: add_taxa_names
  - name: add_relative_clade_information
  - name: remove_tree

training:
    # mlflow_experiment_name: weight_sharing_fraction_yule_10

    splitting_config:
      train_fraction: 0.7
      test_fraction: 0.15

    dataloader_config:
      batch_size: 512
      shuffle: true

    optimizer_config:
      name: adamw
      lr: 0.001
      weight_decay: 0.05
    
    model_config:
      name: weight_sharing_tree_flow
      num_blocks: 8
      mask_fraction: 0.3
      height_model_name: lognormal
      encoding: fractions
      conditioner_dropout: 0.0

    trainer_config:
      max_epochs: 20
