run_name: debug_setup

data_set:
  name: tree_datasets
  directory: data/mcmc_runs
  glob: "yule-10*.trees"
  max_files: 1

preprocessing:
  - name: add_taxa_names
  - name: add_clade_information
  - name: remove_tree

training:
    comet_project_name: debug_setup

    splitting_config:
      train_fraction: 0.7
      test_fraction: 0.15

    dataloader_config:
      batch_size: 256
      shuffle: true
    
    optimizer_config:
      name: adam
    
    model_config:
      name: conditional_tree_flow
      num_blocks: 10
      mask_fraction: 0.5
      context_embedding_size: 8

    trainer_config:
      max_epochs: 100
