run_name: weight_sharing_yule_20

data_set:
  name: tree_datasets
  directory: data/mcmc_runs
  glob: "yule-20_197.trees"
  max_files: 100

preprocessing:
  - name: add_taxa_names
  - name: add_relative_clade_information
  - name: remove_tree

training:
    mlflow_experiment_name: weight_sharing_yule_20

    splitting_config:
      train_fraction: 0.8
      test_fraction: 0.1

    dataloader_config:
      batch_size: 128
      shuffle: true

    optimizer_config:
      name: adamw
      lr: 0.001
      weight_decay: 0.05
    
    model_config:
      name: weight_sharing_tree_flow
      num_blocks: 8
      mask_fraction: 0.5
      height_model_name: lognormal
      encoding: fractions
      conditioner_dropout: 0.0

    trainer_config:
      max_epochs: 50
