run_name: beta_ws_optuna_yule_10_5

num_trials: 100

data_set:
  name: tree_datasets
  directory: data/mcmc_runs
  glob: "yule-10_5.trees"
  max_files: 100

preprocessing:
  - name: add_taxa_names
  - name: add_relative_clade_information
  - name: remove_tree

training:
    mlflow_experiment_name: beta_ws_optuna_yule_10_5

    splitting_config:
      train_fraction: 0.7
      test_fraction: 0.15

    dataloader_config:
      batch_size: 512

      shuffle: true

    optimizer_config:
      name: adamw
      lr:
        sampler: log_uniform
        min: 0.0001
        max: 0.01
      weight_decay:
        sampler: uniform
        min: 0.001
        max: 0.1
    
    model_config:
      name: weight_sharing_tree_flow
      num_blocks:
        sampler: randint
        min: 1
        max: 8
      mask_fraction:
        sampler: uniform
        min: 0.2
        max: 0.8
      conditioner_num_layers: 2
      conditioner_dropout:
        sampler: choice
        options: [0.0, 0.25, 0.5]

    trainer_config:
      max_epochs: 30
